// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYGryoHqehvxwkyBx1g8hTqB6A67wl_Y',
    appId: '1:449008129097:web:9b01017adaaffd148bdb98',
    messagingSenderId: '449008129097',
    projectId: 'creditcardflutter',
    authDomain: 'creditcardflutter.firebaseapp.com',
    storageBucket: 'creditcardflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZrYRD0REEC7uFRAqV3GQ7RRZC8fMt3I',
    appId: '1:449008129097:android:03db8672a585f09d8bdb98',
    messagingSenderId: '449008129097',
    projectId: 'creditcardflutter',
    storageBucket: 'creditcardflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvUF2PmF0kd1VqU0aoAjL4pDpf2DxgUg',
    appId: '1:449008129097:ios:7ed323147c6dbec48bdb98',
    messagingSenderId: '449008129097',
    projectId: 'creditcardflutter',
    storageBucket: 'creditcardflutter.firebasestorage.app',
    iosBundleId: 'com.example.vbtStaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvUF2PmF0kd1VqU0aoAjL4pDpf2DxgUg',
    appId: '1:449008129097:ios:7ed323147c6dbec48bdb98',
    messagingSenderId: '449008129097',
    projectId: 'creditcardflutter',
    storageBucket: 'creditcardflutter.firebasestorage.app',
    iosBundleId: 'com.example.vbtStaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtYGryoHqehvxwkyBx1g8hTqB6A67wl_Y',
    appId: '1:449008129097:web:7ac86cd06f315fca8bdb98',
    messagingSenderId: '449008129097',
    projectId: 'creditcardflutter',
    authDomain: 'creditcardflutter.firebaseapp.com',
    storageBucket: 'creditcardflutter.firebasestorage.app',
  );
}
